server:
  port: 8181
spring:
  thymeleaf:
    mode: HTML5
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    # memory h2 config
    url: jdbc:h2:mem:~/test
    username: sa
    password: colin_test
    # you can config init table and data here
#    schema: classpath:sql/schema.sql
#    data: classpath:sql/data.sql
  jpa:
    database: H2
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
      console:
        path: /h2-console
        enabled: true
logging:
  file: myapplication.log
